
INSERT INTO TIPOPLAN
(tipo)
VALUES
('N/A');

INSERT INTO TIPOPLAN
(tipo)
VALUES
('PROMOCION_PARTICULAR');

INSERT INTO TIPOPLAN
(tipo)
VALUES
('LARGA_ESTADIA');


INSERT INTO TIPOPLAN
(tipo)
VALUES
('TIEMPO_COMPARTIDO');

INSERT INTO TIPOPLAN
(tipo)
VALUES
('TODO_INCLUIDO');

INSERT INTO TIPODOCUMENTO
(tipo)
VALUES
('CC');

INSERT INTO TIPODOCUMENTO
(tipo)
VALUES
('TI');

INSERT INTO TIPODOCUMENTO
(tipo)
VALUES
('TE');
INSERT INTO TIPOUSUARIO
(TIPO)
VALUES
('CLIENTE');
INSERT INTO TIPOUSUARIO
(TIPO)
VALUES
('RECEPCIONISTA');
INSERT INTO TIPOUSUARIO
(TIPO)
VALUES
('EMPLEADO');
INSERT INTO TIPOUSUARIO
(TIPO)
VALUES
('ADMINISTRADOR');
INSERT INTO TIPOUSUARIO
(TIPO)
VALUES
('GERENTE');

INSERT INTO USUARIO
(nombre,documento,tipoplan, tipodocumento,tipousuario,login,contrasena)
VALUES
('SOYADMIN',1000827182,2,2,4,'ADMIN','hello');

INSERT INTO USUARIO
(nombre,documento,tipoplan, tipodocumento,tipousuario,login,contrasena)
VALUES
('CLIENTE',100082719352,2,2,1,'CLIENTE','hello');

INSERT INTO USUARIO
(nombre,documento,tipoplan, tipodocumento,tipousuario,login,contrasena)
VALUES
('RECEPCIONISTA',10002347182,2,2,2,'RECEPCIONISTA','hello');
INSERT INTO USUARIO
(nombre,documento,tipoplan, tipodocumento,tipousuario,login,contrasena)
VALUES
('EMPLEADO',11052347182,2,2,3,'EMPLEADO','hello');
INSERT INTO USUARIO
(nombre,documento,tipoplan, tipodocumento,tipousuario,login,contrasena)
VALUES
('GERENTE',11052347182,2,2,5,'GERENTE','hello');

INSERT INTO TIPOHABITACION
(TIPO, PRECIO, DESCRIPCION)
VALUES
('SUITEPRESIDENCIAL',12341,'caracteristicas:....');

INSERT INTO TIPOHABITACION
(TIPO, PRECIO, DESCRIPCION)
VALUES
('SUITE',123,'caracteristicas:....');

INSERT INTO TIPOHABITACION
(TIPO, PRECIO, DESCRIPCION)
VALUES
('FAMILIAR',123,'caracteristicas:....');

INSERT INTO TIPOHABITACION
(TIPO, PRECIO, DESCRIPCION)
VALUES
('DOBLE',123,'caracteristicas:....');

INSERT INTO TIPOHABITACION
(TIPO, PRECIO, DESCRIPCION)
VALUES
('SIMPLE',123,'caracteristicas:....');
INSERT INTO CADENAHOTELERA
(NOMBRE)
VALUES
('MARRIOT');
INSERT INTO HOTEL
(NOMBRE, ESTRELLAS,CADENAHOTELERA)
VALUES
('BELLAVISTA', 4, 1);
INSERT INTO HABITACION
(TIPO, HOTEL,numeroHabitacion,valorAPagar)
VALUES
(1,1,765,0);
INSERT INTO HABITACION
(TIPO, HOTEL,numeroHabitacion,valorAPagar)
VALUES
(1,1,763,0);

INSERT INTO PERSONASHABITACION
(IDHABITACION, FECHAENTRADA, FECHASALIDA,USO)
VALUES
(1,TO_TIMESTAMP('2014-07-02 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),TO_TIMESTAMP('2014-07-02 06:14:00.742000000', 'YYYY-MM-DD HH24:MI:SS.FF'),1);

COMMIT;

